[project]
name = "single-pool-faktory"
description = ""
authors = []
telemetry = false
cache_dir = "./.cache"

requirements = [
    {contract_id = "SP2VG7S0R4Z8PYNYCAQ04HCBX1MH75VT11VXCWQ6G.built-on-bitcoin-stxcity"},
]

[contracts.bob-single-faktory]
path = 'contracts/bob-single-faktory.clar'
clarity_version = 3
epoch = 'latest'

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
