[project]
name = 'single-pool-faktory'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-deposit'

[contracts.bob-faktory-pool]
path = 'contracts/bob-faktory-pool.clar'
clarity_version = 3
epoch = '3.1'

[contracts.bob-single-faktory]
path = 'contracts/bob-single-faktory.clar'
clarity_version = 3
epoch = '3.1'

[contracts.built-on-bitcoin-stxcity]
path = 'contracts/built-on-bitcoin-stxcity.clar'
clarity_version = 3
epoch = '3.1'

[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 3
epoch = '3.1'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
