[project]
name = 'single-pool-faktory'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.b-faktory]
path = 'contracts/b-faktory.clar'
clarity_version = 3
epoch = '3.1'

[contracts.b-faktory-pool]
path = 'contracts/b-faktory-pool.clar'
clarity_version = 3
epoch = '3.1'

[contracts.b-single-faktory]
path = 'contracts/b-single-faktory.clar'
clarity_version = 3
epoch = '3.1'

[contracts.bob-faktory-pool]
path = 'contracts/bob-faktory-pool.clar'
clarity_version = 3
epoch = '3.1'

[contracts.bob-single-faktory]
path = 'contracts/bob-single-faktory.clar'
clarity_version = 3
epoch = '3.1'

[contracts.built-on-bitcoin-stxcity]
path = 'contracts/built-on-bitcoin-stxcity.clar'
clarity_version = 3
epoch = '3.1'

[contracts.flat-earth-stxcity]
path = 'contracts/flat-earth-stxcity.clar'
clarity_version = 3
epoch = '3.1'

[contracts.flat-single-faktory]
path = 'contracts/flat-single-faktory.clar'
clarity_version = 3
epoch = '3.1'

[contracts.flatearth-faktory-pool]
path = 'contracts/flatearth-faktory-pool.clar'
clarity_version = 3
epoch = '3.1'

[contracts.frog-faktory]
path = 'contracts/frog-faktory.clar'
clarity_version = 3
epoch = '3.1'

[contracts.froggy-faktory-pool]
path = 'contracts/froggy-faktory-pool.clar'
clarity_version = 3
epoch = '3.1'

[contracts.froggy-single-faktory]
path = 'contracts/froggy-single-faktory.clar'
clarity_version = 3
epoch = '3.1'

[contracts.pepe-faktory-pool]
path = 'contracts/pepe-faktory-pool.clar'
clarity_version = 3
epoch = '3.1'

[contracts.pepe-single-faktory]
path = 'contracts/pepe-single-faktory.clar'
clarity_version = 3
epoch = '3.1'

[contracts.sbtc-token]
path = 'contracts/sbtc-token.clar'
clarity_version = 3
epoch = '3.1'

[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 3
epoch = '3.1'

[contracts.skullcoin-faktory-pool]
path = 'contracts/skullcoin-faktory-pool.clar'
clarity_version = 3
epoch = '3.1'

[contracts.skullcoin-stxcity]
path = 'contracts/skullcoin-stxcity.clar'
clarity_version = 3
epoch = '3.1'

[contracts.skullcoin-single-faktory]
path = 'contracts/skullcoin-single-faktory.clar'
clarity_version = 3
epoch = '3.1'

[contracts.tokensoft-token-v4k68639zxz]
path = 'contracts/tokensoft-token-v4k68639zxz.clar'
clarity_version = 3
epoch = '3.1'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = true
callee_filter = true

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
