[project]
name = 'single-pool-faktory'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.bob-faktory-pool]
path = 'contracts/bob-faktory-pool.clar'
clarity_version = 3
epoch = '3.1'

[contracts.bob-single-faktory]
path = 'contracts/bob-single-faktory.clar'
clarity_version = 3
epoch = '3.1'

[contracts.built-on-bitcoin-stxcity]
path = 'contracts/built-on-bitcoin-stxcity.clar'
clarity_version = 3
epoch = '3.1'

[contracts.flat-earth-stxcity]
path = 'contracts/flat-earth-stxcity.clar'
clarity_version = 3
epoch = '3.1'

[contracts.flat-single-faktory]
path = 'contracts/flat-single-faktory.clar'
clarity_version = 3
epoch = '3.1'

[contracts.flatearth-faktory-pool]
path = 'contracts/flatearth-faktory-pool.clar'
clarity_version = 3
epoch = '3.1'

[contracts.sbtc-token]
path = 'contracts/sbtc-token.clar'
clarity_version = 3
epoch = '3.1'

[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 3
epoch = '3.1'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = true
callee_filter = true

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
